[patch]
name = GoldenEye test stack
; Apply files in order.
file_1 = unlock_all_levels.ips
type = ips

[compatibility]
; GoldenEye 007 (USA) check code from your ROM header.
expected_check_code = 0xDCBC50D109FD1AA3
